AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  burguer-place-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BurguerDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      Engine: postgres
      EngineVersion: "16.1"
      DBInstanceClass: db.t3.micro
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: burguer-db
      DBName: burguer
      ManageMasterUserPassword: true
      MasterUsername: flipper

  BurguerPlaceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn: BurguerDBInstance
    Properties:
      PackageType: Image
      CodeUri: '.'
      Handler: dist/interfaces/function/index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CreateRecipe:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /recipe
            Method: post
        ListRecipe:
          Type: Api
          Properties:
            Path: /recipe
            Method: get
        GetRecipe:
          Type: Api
          Properties:
            Path: /recipe/{id}
            Method: get
        DeleteRecipe:
          Type: Api
          Properties:
            Path: /recipe/{id}
            Method: delete
      Environment:
        Variables:
          DB_HOST: !GetAtt BurguerDBInstance.Endpoint.Address
          DB_PORT: !GetAtt BurguerDBInstance.Endpoint.Port
          DB_NAME: !GetAtt BurguerDBInstance.DBName
          DB_USER: !GetAtt BurguerDBInstance.MasterUsername
          DB_PASS_ARN: !GetAtt BurguerDBInstance.MasterUserSecret.SecretArn
          DB_PASS:

    Metadata: # Manage docker metadata
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for create recipe"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BurguerPlaceFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt BurguerPlaceFunction.Arn
  BurguerPlaceFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt BurguerPlaceFunctionRole.Arn
